language: android
sudo: true
jdk: openjdk7

android:
    components:
        - tools
        - platform-tools
        - build-tools-27.0.3
        - android-27
        - extra-android-m2repository
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule init && git submodule update

script:
  - ./gradlew assembleRelease

before_deploy:
  - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/pixelbar-app-${TRAVIS_TAG}.apk
  - mv app/build/outputs/mapping/release/mapping.txt app/build/outputs/apk/pixelbar-mapping-${TRAVIS_TAG}.txt

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
    - app/build/outputs/apk/pixelbar-app-${TRAVIS_TAG}.apk
    - app/build/outputs/apk/pixelbar-mapping-${TRAVIS_TAG}.txt
  skip_cleanup: true
  on:
    tags: true

# branches:
#   only:
#    - master